homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /config/certificate.pem
  ssl_key: /config/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

discovery:
  ignore:
    - apple_tv

#introduction:
frontend:
config:
updater:
conversation:
history:
logbook:
map:
sun:
#emulated_hue:
snips:

#alexa:
#  smart_home:
#    filter:
#      include_domains:
#        - light
#      exclude_entities:
#        - light.family_room
#        - light.jacobs_room
#        - light.kaylies_room
#        - light.master_bedroom
#        - light.office
#        - light.floor_lamp_left_bottom
#        - light.floor_lamp_left_top
#        - light.floor_lamp_right_bottom
#        - light.floor_lamp_right_top

panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:nodejs
    url: !secret nodered_hostname
#  pihole:
#    title: Pi-hole
#    icon: mdi:block-helper
#    url: !secret pihole_hostname

#tts:
#  - platform: google
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: !secret aws_region
#    text_type: ssml
#    voice: Brian

#media_player:
#  platform: mpd
#  host: !secret mopidy_hostname

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_prefix: homeassistant

hue:
  bridges:
    - host: !secret huebridge_hostname
      allow_unreachable: True
#      allow_in_emulated_hue: False
      allow_hue_groups: True

light: !include_dir_list lights/
switch: !include_dir_list switches/
#sensor: !include_dir_list sensors/
group: !include_dir_merge_named groups/
#automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
intent_script: !include_dir_merge_named intents/
